'use client'

import { FormEvent, useState } from 'react'

export default function SignupPage(){
 const [form,setForm]=useState({businessName:'',name:'',email:'',password:'',industry:''})
 const [error,setError]=useState('')
 const [loading,setLoading]=useState(false)
 async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);const r=await fetch('/api/crm/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setLoading(false);if(!r.ok){setError(d.error||'Unable to create workspace');return}window.location.href='/crm/dashboard'}
 return <main className="auth-page"><section className="auth-card"><div className="auth-brand"><span className="crm-mark">M</span><strong>Market Method</strong></div><span className="eyebrow">NEW WORKSPACE</span><h1>Create your workspace</h1><p>Set up the business account that will own your contacts, pipeline, conversations, tasks, and customer history.</p><form className="auth-form"><div className="auth-grid"><div><label>Business name</label><input value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})} required/></div><div><label>Your name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div></div><label>Email address</label><input type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><label>Password</label><input type="password" autoComplete="new-password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><label>Industry</label><select value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})}><option value="">Choose an industry</option><option>Automotive</option><option>Cleaning</option><option>Landscaping</option><option>Home Services</option><option>Professional Services</option><option>Other</option></select>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={loading} onClick={submit}>{loading?'Creating workspace...':'Create workspace'}</button></form><p className="auth-switch">Already have a workspace? <a href="/crm/login">Sign in</a></p></section></main>
}
